version: '3'
services:
  traefik:
    image: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.ctfd.address=:443"
      - "--certificatesresolvers.ctfdcertresolvers.acme.tlschallenge=false"
      - "--certificatesresolvers.ctfdcertresolvers.acme.email=postmaster@idcyberskills.com"
      - "--certificatesresolvers.ctfdcertresolvers.acme.storage=/letsencrypt/acme.json"
    ports:
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik/letsencrypt:/letsencrypt
    networks:
      - internal
      - default

  ctfd:
    image: ctfd/ctfd
    ports:
      - 8000:8000
    environment:
      - SQLALCHEMY_MAX_OVERFLOW=100
      - REVERSE_PROXY=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ctfd.rule=Host(`ctfd.idcyberskills.com`)"
      - "traefik.http.routers.ctfd.entrypoints=ctfd"
      - "traefik.http.routers.ctfd.tls.certresolver=ctfdcertresolvers"
    networks:
        internal:

  db:
    image: mariadb:10.4.12
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
        internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
    - ./data/redis:/data
    networks:
        internal:

networks:
    default:
    internal:
        internal: true